### ISSUE TITLE
Unable to send to Hue Bridge Output

### ISSUE THREAD

**Issue by aiotea** [sinedied/dmx-hue#16]
Hi Sinedied, thanks for making this! 

I've installed the package and QLC+ based on your recommendation. But I am stuck at the next step .... In QLC, I don't see the hue bridge listed as an output IP. I can't figure out how to reach it to send light values to reach the Hue lights.   Where am I supposed to send the DMX to out of QLC?

Any advice is much appreciated!

**Comment by sinedied** [comment]
If you are running them on the same machine, you have to start `dmx-hue` and keep it running before starting the QLC+ app, otherwise QLC+ will use the port to setup its own node server that will conflict with dmx-hue.

Once dmx-hue is started, you can start QLC+ and the node should appear in the list directly.
You should also make sure that dmx-hue and QLC runs on the same network.
