### ISSUE TITLE
Keeps crashing 

### ISSUE THREAD

**Issue by patrickmac110** [sinedied/dmx-hue#44]
We have about 20 hue fixtures that we control for several hours once a week and also we usually change all of these all at once. I have the dmx-hue app running on a raspberry pi. About once every week, the program crashes and just stops working. We're running the pi in a headless mode, so I'm not able to see any outputs when this happens, so I'm wondering if there are any logs and where/how to find those.

**Comment by sinedied** [comment]
You could always redirect the log output to a file `dmx-hue > logs.txt 2>&1` this way any logs would be written to the `logs.txt` file, and that may help understand what's causing the crash.
If you happen to get the logs with the error, please post it here.

**Comment by scenkner** [comment]
I just started using this. I too am having regular crashing. Here's my terminal output. It crashed in less than a minute every time. Only two fixtures running on a fairly modern PC.
0
DMX addresses on universe 0:
 1: Hue color lamp 1 (Hue ID: 2)
 4: Hue color lamp 2 (Hue ID: 3)

ArtNet node started (CTRL+C to quit)
/usr/lib/node_modules/dmx-hue/node_modules/node-hue-api/lib/api/http/Transport.js:75
          throw new ApiError(errors[0]);
                ^

ApiError: Internal error, 404
    at /usr/lib/node_modules/dmx-hue/node_modules/node-hue-api/lib/api/http/Transport.js:75:17 {
  _hueError: HueError {
    payload: {
      message: 'Internal error, 404',
      type: 901,
      address: '/lights/2/state/effect',
      description: 'Internal error, 404'
    }
  }
}

Node.js v20.9.0


edit: changing qlcplus from DMX control to function control with thresholds removed the immediate crashes. Probably due to the reduced number of transitions being sent to dmx-hue.

**Comment by sinedied** [comment]
Thanks for the log!
There's nothing I can do about fixing the upstreaming issue, as it's probably related to the bridge being temporarily unavailable or overloaded, but at least I can catch the error and prevent dmx-hue from crashing.
Will try to fix it ASAP.
